### ISSUE TITLE
About u-blox support

### ISSUE THREAD

**Issue by JinghaoZhao** [PodgroupConnectivity/sim-applet-apn-autoconf#1]
Hello,
I'm testing a similar sim toolkit applet that can send at commands to the terminal. I'm using a u-blox board which shows it can support RUN AT COMMAND from the terminal profile, but when I select the corresponding item it will return +STKCNF: 52,48,255,144, which is "Command beyond terminal's capabilities" in the standard. I find that you met similar issues and post a question on the u-blox forum. Could you tell me if you successfully run it on an u-blox board? Is there any response from the u-blox support team?

Thanks a lot!

**Comment by dielenram** [comment]
Hello,

Unfortunately, we couldn't make it work and the u-blox support team didn't provide us with a solution. As we described in the post, the device seems to return the AT COMMAND via serial port, but the AT COMMAND isn't effectively executed. We couldn't move the project forward indeed.

In your case, it might be possible the device is rejecting the command for some reason but I don't think it doesn't support the proactive STK RUN AT COMMAND. It might be worth trying different AT COMMANDs and different configurations of the applet. For example, trying to trigger the applet after an event such as STATUS in order to discard possible interference with the item selection.

I hope it helps, I would really appreciate if you let us know how your test goes because we would be interested in reopening this project.

Thanks.

**Comment by JinghaoZhao** [comment]
> Hello,
> 
> Unfortunately, we couldn't make it work and the u-blox support team didn't provide us with a solution. As we described in the post, the device seems to return the AT COMMAND via serial port, but the AT COMMAND isn't effectively executed. We couldn't move the project forward indeed.
> 
> In your case, it might be possible the device is rejecting the command for some reason but I don't think it doesn't support the proactive STK RUN AT COMMAND. It might be worth trying different AT COMMANDs and different configurations of the applet. For example, trying to trigger the applet after an event such as STATUS in order to discard possible interference with the item selection.
> 
> I hope it helps, I would really appreciate if you let us know how your test goes because we would be interested in reopening this project.
> 
> Thanks.

Thanks a lot for your help! I will share with you the results if it's successful!
